"""
FE-09: Flow Explorer — beginner-friendly runtime flow viewer.
Shows readable logs and run reports generated by the pipeline.
"""

from pathlib import Path
import json

import streamlit as st

from config.settings import FLOW_LOG_PATH, LOGS_DIR, REPORTS_DIR


def _read_text(path: Path, default: str = "") -> str:
    if not path.exists():
        return default
    return path.read_text(encoding="utf-8")


def _list_report_files(suffix: str) -> list[Path]:
    if not REPORTS_DIR.exists():
        return []
    return sorted(REPORTS_DIR.glob(f"run_*.{suffix}"), reverse=True)


def _render_flow_log():
    st.subheader("Flow Log")
    st.caption("Human-readable stage-by-stage runtime narration from the latest runs.")

    if not FLOW_LOG_PATH.exists():
        st.info("No flow log found yet. Run the pipeline from the Run Pipeline page first.")
        return

    text = _read_text(FLOW_LOG_PATH)
    lines = text.splitlines()
    st.caption(f"{len(lines)} total lines in {FLOW_LOG_PATH.name}")

    tail_lines = st.slider("Show last N log lines", min_value=20, max_value=500, value=120, step=20)
    tail = "\n".join(lines[-tail_lines:]) if lines else ""
    st.code(tail, language="text")

    st.download_button(
        "Download Full Flow Log",
        data=text.encode("utf-8"),
        file_name=FLOW_LOG_PATH.name,
        mime="text/plain",
    )


def _render_report_summary():
    st.subheader("Latest Run Summary")
    latest_md = REPORTS_DIR / "latest_run_report.md"
    latest_json = REPORTS_DIR / "latest_run_report.json"

    col1, col2 = st.columns(2)
    with col1:
        if latest_md.exists():
            st.markdown(_read_text(latest_md, ""))
        else:
            st.info("No Markdown run report found yet.")

    with col2:
        if latest_json.exists():
            payload = json.loads(_read_text(latest_json, "{}") or "{}")
            metrics = payload.get("metrics", {})
            st.metric("Total Processed", int(metrics.get("total_processed", 0)))
            st.metric("Accuracy", f"{float(metrics.get('accuracy', 0.0)):.0%}")
            st.metric("Average Confidence", f"{float(metrics.get('avg_confidence', 0.0)):.0%}")
            st.metric("Processing Time", f"{float(metrics.get('processing_time_seconds', 0.0)):.1f}s")
        else:
            st.info("No JSON run report found yet.")


def _render_report_history():
    st.subheader("Run Report History")

    md_reports = _list_report_files("md")
    json_reports = _list_report_files("json")

    if not md_reports and not json_reports:
        st.info("No historical run reports found yet.")
        return

    tab1, tab2 = st.tabs(["Markdown Reports", "JSON Reports"])

    with tab1:
        if md_reports:
            selected_md = st.selectbox("Select markdown report", [p.name for p in md_reports])
            md_path = REPORTS_DIR / selected_md
            md_text = _read_text(md_path)
            st.markdown(md_text)
            st.download_button(
                "Download Markdown Report",
                data=md_text.encode("utf-8"),
                file_name=selected_md,
                mime="text/markdown",
                key="download_md_report",
            )
        else:
            st.caption("No markdown reports available.")

    with tab2:
        if json_reports:
            selected_json = st.selectbox("Select JSON report", [p.name for p in json_reports])
            json_path = REPORTS_DIR / selected_json
            json_text = _read_text(json_path)
            st.code(json_text, language="json")
            st.download_button(
                "Download JSON Report",
                data=json_text.encode("utf-8"),
                file_name=selected_json,
                mime="application/json",
                key="download_json_report",
            )
        else:
            st.caption("No JSON reports available.")


def render():
    st.header("Flow Explorer")
    st.markdown(
        "Use this page to understand pipeline execution flow with friendly logs and run reports. "
        "It is especially useful for newcomers to Agentic AI."
    )

    with st.expander("How to read this page (Beginner Help)", expanded=True):
        st.markdown(
            "**Confidence**: How sure the classifier is about the category. "
            "Higher is usually better.\n\n"
            "**Accuracy**: How closely current run outputs match expected labels in the mock evaluation file. "
            "In this project, it combines category and priority matching.\n\n"
            "**Duplicates**: Tickets that likely describe an already-seen issue/request. "
            "Use this to avoid creating repeated engineering tasks.\n\n"
            "**Quality Score**: Ticket quality rating from the quality-critic stage. "
            "Higher scores mean clearer, more complete tickets.\n\n"
            "**Flow Log**: Time-ordered, stage-by-stage narration of what the pipeline did.\n\n"
            "**Run Reports**: Summaries generated after each run. Use Markdown report for quick reading, "
            "and JSON report for structured analysis."
        )

        st.markdown(
            "**Suggested reading order for first-time users**\n"
            "1. Latest Run Summary\n"
            "2. Flow Log (last 100-200 lines)\n"
            "3. Historical reports to compare runs"
        )

    st.caption(f"Logs folder: {LOGS_DIR}")
    st.caption(f"Reports folder: {REPORTS_DIR}")

    _render_flow_log()
    st.divider()
    _render_report_summary()
    st.divider()
    _render_report_history()
